### ISSUE TITLE
[버그] 

### ISSUE THREAD

**Issue by jyman7811** [tlfn/jeonjeok#5]
**버그 설명**
베이스 증폭 수치가 제대로 표시되지않음

**기대되는 결과**
베이스 증폭 수치를 제대로 보여줌

**오류로 인한 결과**
베이스 수치가 1임

**재현 방법**

1.베이스를 소수로 증폭함

2.!bb로 베이스를 확인

3.

**스크린샷 (옵션)**

**Comment by tlfn** [comment]
Already fixed
